### ISSUE TITLE
Create dynamic tax years on headings for benefits section and income section

### ISSUE THREAD

**Issue by MatthewAlexanderBeck** [hmrc/claim-tax-refund-frontend#136]
### Scrum details
Story points: 8
Jira ticket number: 

### Description
Create dynamic tax years on headings after the user selects a tax year. This will create synamic headings based on their selection e.g.
How much Jobseeker's Allowance did you get during the tax year 6 April 2016 to 5 April 2017

**Comment by oliverslade** [comment]
Moving over to JIRA
