### ISSUE TITLE
Adding hint text to details of other benefit and details of other income pages

### ISSUE THREAD

**Issue by oliverslade** [hmrc/claim-tax-refund-frontend#153]
### Scrum details
Story points: 1

### Description
To add the hint text that is already in the messages file to each of these views

**Comment by farhad-islam** [comment]
Changes required in two areas:-
-OtherBenefitsDetailsAndAmountView
-OtherIncomeDetailsAndIncomeView

**Comment by oliverslade** [comment]
Moving over to JIRA
